//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Doctors_Name { get; set; }
        public string Specialization { get; set; }
        public System.DateTime Avail_Date { get; set; }
        public string Avail_Time { get; set; }
        public decimal Consult_Fees { get; set; }
    }
}
