//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBill.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public int Id { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string First_Name { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string Last_Name { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]

        [DataType(DataType.Date)]
        public System.DateTime DoB { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string Gender { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public long Contact_Number { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string Email { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string User_Id { get; set; }



        [Required(ErrorMessage = "Please update the highlighted mandatory field(s)")]
        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
