//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public int Id { get; set; }
        public Nullable<int> patientId { get; set; }
        public string MedicineName { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> totalCost { get; set; }
    }
}
