//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBill.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [DisplayName("First Name")]
        public string FName { get; set; }
        [Required]
        [DisplayName("Last Name")]
        public string LName { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date Of Birth")]
        public System.DateTime Dob { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        [DisplayName("Contact Number")]
        public long ContactNumber { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string User_Id { get; set; }
        [Required]
        public string Password { get; set; }
       public string status { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
