//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotBill
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string DoctorsName { get; set; }
        public Nullable<decimal> ConsFees { get; set; }
        public string serviceName { get; set; }
        public Nullable<decimal> Servcost { get; set; }
        public Nullable<decimal> RoomCharges { get; set; }
        public Nullable<decimal> PharmacyCharges { get; set; }
        public Nullable<decimal> totalCost { get; set; }
    }
}
